FROM python:alpine
WORKDIR /usr/app/src
COPY /database/loader.py ./
RUN apk update && \
    apk add --no-cache --virtual build-deps gcc python3-dev musl-dev && \
    apk add postgresql-dev
RUN pip install requests && \
    pip install psycopg2
CMD [ "python", "loader.py"]
